export interface Country {
  code: string;
  name: string;
  flag: string;
  region: string;
}

export const COUNTRIES: Country[] = [
  { code: "CN", name: "China", flag: "🇨🇳", region: "Asia" },
  { code: "IN", name: "India", flag: "🇮🇳", region: "Asia" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", region: "Asia" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", region: "Europe/Asia" },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Middle East",
  },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", region: "Africa" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", region: "Africa" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", region: "Africa" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", region: "Africa" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", region: "Europe" },
  { code: "US", name: "United States", flag: "🇺🇸", region: "Americas" },
  { code: "DE", name: "Germany", flag: "🇩🇪", region: "Europe" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", region: "Asia" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", region: "Asia" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", region: "Asia" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", region: "Asia" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", region: "Asia" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", region: "Asia" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", region: "Africa/Middle East" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", region: "Africa" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", region: "Africa" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", region: "Africa" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", region: "Africa" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", region: "Middle East" },
  { code: "IT", name: "Italy", flag: "🇮🇹", region: "Europe" },
  { code: "FR", name: "France", flag: "🇫🇷", region: "Europe" },
  { code: "JP", name: "Japan", flag: "🇯🇵", region: "Asia" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", region: "Asia" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", region: "Asia" },
  { code: "AL", name: "Albania", flag: "🇦🇱", region: "Europe" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", region: "Africa" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", region: "Europe" },
  { code: "AO", name: "Angola", flag: "🇦🇴", region: "Africa" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", region: "Americas" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", region: "Americas" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", region: "Asia" },
  { code: "AU", name: "Australia", flag: "🇦🇺", region: "Oceania" },
  { code: "AT", name: "Austria", flag: "🇦🇹", region: "Europe" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", region: "Asia" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", region: "Americas" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", region: "Middle East" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", region: "Americas" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", region: "Europe" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", region: "Europe" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", region: "Americas" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", region: "Africa" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", region: "Asia" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", region: "Americas" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", region: "Europe" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", region: "Africa" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", region: "Americas" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", region: "Asia" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", region: "Europe" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", region: "Africa" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", region: "Africa" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", region: "Africa" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", region: "Asia" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", region: "Africa" },
  { code: "CA", name: "Canada", flag: "🇨🇦", region: "Americas" },
  {
    code: "CF",
    name: "Central African Republic",
    flag: "🇨🇫",
    region: "Africa",
  },
  { code: "TD", name: "Chad", flag: "🇹🇩", region: "Africa" },
  { code: "CL", name: "Chile", flag: "🇨🇱", region: "Americas" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", region: "Americas" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", region: "Africa" },
  { code: "CG", name: "Congo", flag: "🇨🇬", region: "Africa" },
  { code: "CD", name: "DR Congo", flag: "🇨🇩", region: "Africa" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", region: "Americas" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", region: "Africa" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", region: "Europe" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", region: "Americas" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", region: "Europe" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", region: "Europe" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", region: "Europe" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", region: "Africa" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", region: "Americas" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", region: "Americas" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", region: "Americas" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", region: "Americas" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", region: "Africa" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", region: "Africa" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", region: "Europe" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", region: "Africa" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", region: "Oceania" },
  { code: "FI", name: "Finland", flag: "🇫🇮", region: "Europe" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", region: "Africa" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", region: "Africa" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", region: "Asia" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", region: "Africa" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", region: "Americas" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", region: "Americas" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", region: "Americas" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", region: "Asia" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", region: "Europe" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", region: "Europe" },
  { code: "IR", name: "Iran", flag: "🇮🇷", region: "Middle East" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", region: "Middle East" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", region: "Europe" },
  { code: "IL", name: "Israel", flag: "🇮🇱", region: "Middle East" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", region: "Americas" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", region: "Middle East" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", region: "Asia" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", region: "Oceania" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", region: "Middle East" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", region: "Asia" },
  { code: "LA", name: "Laos", flag: "🇱🇦", region: "Asia" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", region: "Europe" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", region: "Middle East" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", region: "Africa" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", region: "Africa" },
  { code: "LY", name: "Libya", flag: "🇱🇾", region: "Africa" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", region: "Europe" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", region: "Europe" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", region: "Europe" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", region: "Africa" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", region: "Africa" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", region: "Asia" },
  { code: "ML", name: "Mali", flag: "🇲🇱", region: "Africa" },
  { code: "MT", name: "Malta", flag: "🇲🇹", region: "Europe" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", region: "Oceania" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", region: "Africa" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", region: "Africa" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", region: "Americas" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", region: "Oceania" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", region: "Europe" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", region: "Europe" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", region: "Asia" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", region: "Europe" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", region: "Africa" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", region: "Asia" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", region: "Africa" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", region: "Oceania" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", region: "Asia" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", region: "Europe" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", region: "Oceania" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", region: "Americas" },
  { code: "NE", name: "Niger", flag: "🇳🇪", region: "Africa" },
  { code: "NO", name: "Norway", flag: "🇳🇴", region: "Europe" },
  { code: "OM", name: "Oman", flag: "🇴🇲", region: "Middle East" },
  { code: "PW", name: "Palau", flag: "🇵🇼", region: "Oceania" },
  { code: "PA", name: "Panama", flag: "🇵🇦", region: "Americas" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", region: "Oceania" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", region: "Americas" },
  { code: "PE", name: "Peru", flag: "🇵🇪", region: "Americas" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", region: "Asia" },
  { code: "PL", name: "Poland", flag: "🇵🇱", region: "Europe" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", region: "Europe" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", region: "Middle East" },
  { code: "RO", name: "Romania", flag: "🇷🇴", region: "Europe" },
  { code: "RU", name: "Russia", flag: "🇷🇺", region: "Europe/Asia" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", region: "Africa" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", region: "Americas" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", region: "Americas" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    region: "Americas",
  },
  { code: "WS", name: "Samoa", flag: "🇼🇸", region: "Oceania" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", region: "Europe" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", region: "Africa" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", region: "Africa" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", region: "Europe" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", region: "Africa" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", region: "Africa" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", region: "Europe" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", region: "Europe" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", region: "Oceania" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", region: "Africa" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", region: "Africa" },
  { code: "ES", name: "Spain", flag: "🇪🇸", region: "Europe" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", region: "Asia" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", region: "Africa" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", region: "Americas" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", region: "Europe" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", region: "Europe" },
  { code: "SY", name: "Syria", flag: "🇸🇾", region: "Middle East" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", region: "Asia" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", region: "Asia" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", region: "Asia" },
  { code: "TG", name: "Togo", flag: "🇹🇬", region: "Africa" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", region: "Oceania" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", region: "Americas" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", region: "Africa" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", region: "Asia" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", region: "Oceania" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", region: "Europe" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", region: "Americas" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", region: "Asia" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", region: "Oceania" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", region: "Americas" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", region: "Middle East" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", region: "Africa" },
];
