name = "proof-procure-keeper"
main = "src/index.ts"
compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/1 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "proof-procure-db"
database_id = "a6e45af5-39b1-45ed-bd4b-23752f35ef85"

[vars]
ARC_RPC_URL = "https://mainnet.base.org"
