name = "proof-procure"
main = ".open-next/worker.js"
compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "proof-procure"

[[d1_databases]]
binding = "DB"
database_name = "proof-procure-db"
database_id = "a6e45af5-39b1-45ed-bd4b-23752f35ef85"

[vars]
BASE_RPC_URL = "https://mainnet.base.org"
